[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
marketplace = "H4QHUFUkNQqrCcPQ45cwhPveXtr9mZ1723SZLNX4kvAs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
